// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cnyAcpQNRASTVzZ6hR24wpJV2bEdIMc',
    appId: '1:867082952490:web:3fa5cf5e652f7789f04853',
    messagingSenderId: '867082952490',
    projectId: 'soyganadero-10eb5',
    authDomain: 'soyganadero-10eb5.firebaseapp.com',
    storageBucket: 'soyganadero-10eb5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1mcM6AWAflDchjRdfmDrx7k6YOcC5Ok',
    appId: '1:867082952490:android:06f158aaf85e1a3cf04853',
    messagingSenderId: '867082952490',
    projectId: 'soyganadero-10eb5',
    storageBucket: 'soyganadero-10eb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NB1RH9a4I_6LPzUt8tF8ewmrjyZNqto',
    appId: '1:867082952490:ios:709276439ce4ce53f04853',
    messagingSenderId: '867082952490',
    projectId: 'soyganadero-10eb5',
    storageBucket: 'soyganadero-10eb5.firebasestorage.app',
    iosClientId: '867082952490-cncjlml7dk09n2pnqoo253fvnoli1lh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.manualGanaderoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NB1RH9a4I_6LPzUt8tF8ewmrjyZNqto',
    appId: '1:867082952490:ios:709276439ce4ce53f04853',
    messagingSenderId: '867082952490',
    projectId: 'soyganadero-10eb5',
    storageBucket: 'soyganadero-10eb5.firebasestorage.app',
    iosClientId: '867082952490-cncjlml7dk09n2pnqoo253fvnoli1lh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.manualGanaderoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-cnyAcpQNRASTVzZ6hR24wpJV2bEdIMc',
    appId: '1:867082952490:web:ac8ebf6e2c07ead0f04853',
    messagingSenderId: '867082952490',
    projectId: 'soyganadero-10eb5',
    authDomain: 'soyganadero-10eb5.firebaseapp.com',
    storageBucket: 'soyganadero-10eb5.firebasestorage.app',
  );
}
